name: cd
on:
  push:
    tags:
      - "v*"

jobs:
  plugin-cd:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-cd.yml@main
    secrets: inherit
    with:
      golang-version: "1.24"
